//Localhost 

//Get all events
GET http://localhost:8080/events HTTP/1.1

###
//Get and event by id
GET http://localhost:8080/events/65c56104f896d5e7ea92fc46 HTTP/1.1

### 
//Create a new event
POST http://localhost:8080/events HTTP/1.1
content-type: application/json

{
    "eventName": "Superbowl 59",
    "eventDate": "02/11/2024",
    "paymentRecieved": "Yes",
    "customerName": "Kordell Farley"
}

### update an event
PUT http://localhost:8080/events/ HTTP/1.1


### Delete an event
DELETE http://localhost:8080/ HTTP/1.1


//////////////////////////
///////PRODUCTION/////////
//////////////////////////

###
//Get all events
GET http://cse341-project2-h8z8.onrender.com/contacts HTTP/1.1

###
// Get an event by id
GET http://cse341-project2-h8z8.onrender.com/contacts/65c56104f896d5e7ea92fc46 HTTP/1.1

###
//Create a new event
POST http://cse341-project2-h8z8.onrender.com/contacts HTTP/1.1

###
//Update an event
PUT http://cse341-project2-h8z8.onrender.com/ HTTP/1.1

###
//Delete an event
DELETE http://cse341-project2-h8z8.onrender.com/ HTTP/1.1


