//Localhost 

//Get all events
GET http://localhost:8080/events HTTP/1.1

###
//Get and event by id
GET http://localhost:8080/events/65c56104f896d5e7ea92fc46 HTTP/1.1

### 
//Create a new event
POST http://localhost:8080/events HTTP/1.1
content-type: application/json

{
  "title": "Camp",
  "description": "Teton Summit lodge",
  "date": "2024-07-11",
  "time": "06:30 PM",
  "location": "Grand Teton National Park",
  "attendees": 102

}

### update an event
PUT http://localhost:8080/events/65cfedecee070b0aee89b308 HTTP/1.1
content-type: application/json

{
  "title": "Ward BBQ",
  "description": "Come enjoy some brisket and corn on the cob and get to know your fellow ward members.",
  "time": "05:45 PM",
  "date": "2024-05-04T00:00:00.000Z",
  "location": "Bishops House",
  "attendees": 200
}


### Delete an event
DELETE http://localhost:8080/events/65cfebdeee070b0aee89b303 HTTP/1.1



//////////////////////////
///////PRODUCTION/////////
//////////////////////////

###
//Get all events
GET http://cse341-project2-h8z8.onrender.com/events HTTP/1.1

###
// Get an event by id
GET http://cse341-project2-h8z8.onrender.com/events/65c56104f896d5e7ea92fc46 HTTP/1.1

###
//Create a new event
POST http://cse341-project2-h8z8.onrender.com/events HTTP/1.1

###
//Update an event
PUT http://cse341-project2-h8z8.onrender.com/events HTTP/1.1

###
//Delete an event
DELETE http://cse341-project2-h8z8.onrender.com/events HTTP/1.1


